export const ADD_RESTAURANT = "ADD_RESTAURANT"
export const SYNC_RESTAURANTS = 'SYNC_RESTAURANTS';
export const LOAD_RESTAURANTS = 'LOAD_RESTAURANTS';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';